<a href="https://colab.research.google.com/github/zenon10/ria_codes_vf/blob/main/para_splitter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**Libraries**

In [82]:
import pandas as pd
import re

#**Function**

In [91]:
def para_splitter(input_text_file_path):

    f = open(input_text_file_path, "r", encoding="utf8")
    f=f.read()

    #splitting text file on double new lines
    paragraph = f.split('\n\n')

    #creating dataframe
    df = pd.DataFrame()
    df['para_text'] = paragraph
    
    para_id = []
    is_section_ind = []
    section_id = []
    is_article_ind = []
    article_id = []

#**********************************************************#
    for i in range(len(paragraph)):
        para_id.append(i)
        
    df['para_id'] = para_id
#**********************************************************#  
    for i in df['para_text']:
        if re.match('^[0-9][.][0-9][\s][a-zA-Z]',i):
            is_section_ind.append(1)
        else:
            is_section_ind.append(0)
        if re.match('^[Aa][rR][tT][iI][cC][lL][eE][.][0-9]',i):
            is_article_ind.append(1)
        else:
            is_article_ind.append(0)

    df['is_article_ind'] = is_article_ind
    df['is_section_ind'] = is_section_ind
#**********************************************************# 
    count = 1
    for i in df['is_section_ind']:
        if i == 1:
            section_id.append('s'+str(count))
            count = count +1
        else:
            section_id.append(None)

#**********************************************************#
    count = 1
    for i in df['is_article_ind']:
        if i == 1:
            article_id.append('a'+str(count))
            count = count +1
        else:
            article_id.append(None)

#**********************************************************#
    
    df['section_id'] = section_id
    df['article_id'] = article_id

    # applying ffill() method to fill the missing values
    df['section_id']=df['section_id'].ffill(axis = 0)
    df['article_id']=df['article_id'].ffill(axis = 0)

#**********************************************************#
    df = df[['para_id','para_text','is_article_ind','article_id','is_section_ind','section_id']]

    return df

    # df.to_excel('s04_cctp_montpellier v2_ocr2.xlsx', encoding="utf8" )

In [92]:
input_text_file_path = r'/content/drive/MyDrive/Zenon_POC_OCR/s04_cctp_montpellier v2.txt'
df=para_splitter(input_text_file_path)

In [93]:
df

,para_id,para_text,is_article_ind,article_id,is_section_ind,section_id
0,0,à\n_ L< mises cames\nnd ten,0,None,0,None
1,1,MARCHES PUBLICS DE FOURNITURES COURANTES ET SE...,0,None,0,None
2,2,CAHIER DES CLAUSES TECHNIQUES PARTICULIÈRES,0,None,0,None
3,3,(C.C.T.P.)\n(Commun à tous les lots),0,None,0,None
4,4,Affaire n° 22A0001\nFOURNITURE DE DISPOSITIFS ...,0,None,0,None
...,...,...,...,...,...,...
112,112,Pour les dispositifs médicaux implantables et ...,0,a4,0,s11
113,113,ARTICLE.7 ESSAIS / DEMANDE DE REFERENCEMENT DE...,1,a5,0,s11
114,114,"Pour tout essai de nouveau produit, se référer...",0,a5,0,s11
115,115,Affaire n° 22A0001\nFOURNITURE DE DISPOSITIFS ...,0,a5,0,s11
116,116,Page 9/9\nCCTP\nSecteur juridique le 08/09/2021\n,0,a5,0,s11